runtime: python
env: flex  # This specifies the Flexible Environment

entrypoint: gunicorn --workers 1 --worker-class gevent --timeout 3600 --log-level info --bind :$PORT app:app

instance_class: F2  # Optional: If you want to specify a custom machine type
resources:
  cpu: 4            # Adjust CPU as needed
  memory_gb: 8      # Adjust memory as needed
  disk_size_gb: 10  # Adjust disk size as needed

# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 5

runtime_config:
  operating_system: "ubuntu22"
  python_version: "3.10"  # or whichever version you're targeting

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  CLOUD_STORAGE_BUCKET: olmstead-property-letters
  FLASK_SERVER: app
  FLASK_DEBUG: 1  # Ensure this is set to 0 for production

service_account: fresh-service-account@mail-engine-411414.iam.gserviceaccount.com